ALTER TABLE mail_accounts 
MODIFY COLUMN imap_host VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN imap_port INT DEFAULT NULL,
MODIFY COLUMN imap_use_ssl TINYINT DEFAULT NULL,
MODIFY COLUMN imap_username VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN imap_password_encrypted TEXT DEFAULT NULL,
MODIFY COLUMN smtp_host VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN smtp_port INT DEFAULT NULL,
MODIFY COLUMN smtp_use_tls TINYINT DEFAULT NULL,
MODIFY COLUMN smtp_username VARCHAR(255) DEFAULT NULL,
MODIFY COLUMN smtp_password_encrypted TEXT DEFAULT NULL;
